spring:
 profiles:
  active:
   dev
   
spring:
 profiles: dev
 application:
  name: microservicecloud-config-chenxi-dev
  
spring:
 profiles: test
 application:
  name: microservicecloud-config-chenxi-test